openapi: 3.0.1
info:
  version: 0.1.0
  title: Simple ATM API docs
  contact:
    email: gabrieldzul@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    # Description
    API to handle deposits and withdrawals on the ATM
servers:
  - url: http://localhost:3000/api
    description: Optional localhost
paths:
  /deposits:
    post:
      summary: Create a new deposit
      tags:
        - deposits
      description: |
        Create a new deposit
      operationId: addDeposit
      requestBody:
        content:
          application/json:
            schema:
              title: Deposit Post Request Body
              description: ""
              type: object
              properties:
                banknotes:
                  description: Bank notes denominations to deposit
                  type: object
                  additionalProperties: true
                  example:
                    "1": 10
                    "5": 7
                    "10": 9
                    "50": 3
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                dditionalProperties: true
                example:
                  "1": 10,
                  "2": 0,
                  "5": 7,
                  "10": 9,
                  "25": 0,
                  "50": 3
        "412":
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      status:
                        enum:
                          - 412
                      message:
                        type: string
                        description: A message explaining the error reason
  /withdrawals:
    post:
      summary: Create a new withdrawal
      tags:
        - withdrawals
      description: |
        Create a new withdrawal
      operationId: addWithdrawal
      requestBody:
        content:
          application/json:
            schema:
              title: Withdrawal Post Request Body
              type: object
              description: Bank notes denominations to deposit
              properties:
                amount:
                  enum:
                    - 95
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                dditionalProperties: true
                example:
                  "1": 10
                  "5": 7
                  "10": 9
                  "50": 3
        "412":
          description: Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: object
                    properties:
                      status:
                        enum:
                          - 412
                      message:
                        type: string
                        description: A message explaining the error reason
