openapi: "3.0.1"
info:
  $ref: 'api/info/summary.yml'
servers:
  - url: http://localhost:3000/api
    description: Optional localhost
paths:
  /deposits:
    $ref: "api/deposits/create.yml"
  /withdrawals:
    $ref: "api/withdrawals/create.yml"
